<?php

require_once dirname(__FILE__) . '/../../classes/grade.class.php';

/**
 * Test class for GradeFromFile.
 * Generated by PHPUnit on 2012-02-27 at 17:18:18.
 */
class GradeFromFileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var GradeFromFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	//$this->object = new GradeFromFile("asdf asdf asdf");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @covers GradeFromFile::__get
     * @todo Implement test__get().
     */
    public function test__get() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @covers GradeFromFile::__toString
     * @todo Implement test__toString().
     */
    public function test__toString() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

}

?>
