<?php

require_once dirname(__FILE__) . '/../../classes/rtfgradefile.class.php';

/**
 * Test class for RtfGradeFile.
 * Generated by PHPUnit on 2012-02-26 at 21:45:36.
 */
class RtfGradeFileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RtfGradeFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new RtfGradeFile("Jānis Bērziņš)");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @covers RtfGradeFile::Generate_Content
     */
    public function testGenerate_Content() {
	$this->object->Generate_Content();
	$this->assertNotEmpty($this->object->fileContents, "Failam nevajadzētu sanākt tukšam");
    }

    /**
     * @covers RtfGradeFile::Write_To_Client
     * @depends testGenerate_Content
     */
    public function testWrite_To_Client() {
	$_SERVER['HTTP_USER_AGENT'] = "PHP";
	$this->object->Generate_Content();
	//$this->object->Write_To_Client();
    }

}

?>
